---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-svc
    spec:
      containers:
        - name: apisvc
          image: httpd:latest
          ports:
            - containerPort: 80
              name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: colors
spec:
  gateways:
  - colors
  hosts:
  - colors.demo4591.codefresh.io
  http:
  - route:
    - destination:
        host: colors-color
        port:
          number: 80
      weight: 20
    - destination:
        host: donating-pug-color
        port:
          number: 80
      weight: 80
