---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-svc
    spec:
      containers:
        - name: apisvc
          image: httpd:latest
          ports:
            - containerPort: 80
              name: http
